wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1711122666.0
    t:
      1:
      - 1
      - 49
      - 53
      - 55
      2:
      - 1
      - 49
      - 53
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.10.14
      5: 0.16.4
      8:
      - 2
      - 5
      13: linux-x86_64
