wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1710957098.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      - 64
      2:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      - 64
      3:
      - 17
      - 23
      - 37
      4: 3.8.18
      5: 0.16.4
      6: 4.38.2
      8:
      - 2
      - 5
      13: linux-x86_64
